spring:
  application:
    name: dr-xoshimov
  datasource:
    url: jdbc:postgresql://localhost:5432/dr_xosh_bot
    username: postgres
    password: -098
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
auth:
  key: dcs54csdf8wefsf45232r!sd5af?dff8w7fw8efwefwef8
bot:
  username: dr_xoshimov_bot
  token: 7620327974:AAGaPQzUlNizoXZTRkQA75i4jgLTa3_GFmI
  path: /api/webhook
  group_chat_id: -4683778690
server:
  port: 8040